name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go mod tidy
      run: cd gear; go mod tidy

    - name: Lexer test
      run: cd gear; go test gear/pkg/lexer -v
    
    - name: Parser test
      run: cd gear; 	go test gear/pkg/parser -v 
      
    - name: Docstring parser test
      run: cd gear; 	go test gear/pkg/docparser -v 
      
    - name: Gear build
      run: cd gear;  go build gear/cmd/gear

    - name: Dolphin CLI build
      run: cd gear;  go build gear/cmd/dolphin
      
    - name: Gear parser build
      run:  cd gear; go build gear/cmd/gear_ast
    
    - name: Gear lexer build
      run:  cd gear; go build gear/cmd/gear_lex

    - name: Gear documentation gen build
      run:  cd gear; go build gear/cmd/gear_doc
